#!/bin/bash

# Append it's arglist to $PATH iff the arguments are new to the $PATH variable
function path-append {
    for arg in $@; do
        if ! [[ $PATH =~ "$arg" ]]; then
            PATH="$PATH:$arg"
        fi
    done
}

## ============================================================================
##                                 Settings
## ============================================================================

# BELL SOUND = </3
set bell-style none

# Avoid overlay files
set -o noclobber

# Unveils hidden failures
set -o pipefail

# Update winsize after each command for better line-wrapping
shopt -s checkwinsize

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

## ============================================================================
##                           Environment Variables
## ============================================================================

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM='xterm-256color';
fi;

export EDITOR=nvim

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Have less display colours
# from: https://wiki.archlinux.org/index.php/Color_output_in_console#man
export LESS_TERMCAP_mb=$'\e[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\e[1;33m'     # begin blink
export LESS_TERMCAP_so=$'\e[01;44;37m' # begin reverse video
export LESS_TERMCAP_us=$'\e[01;37m'    # begin underline
export LESS_TERMCAP_me=$'\e[0m'        # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'        # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'        # reset underline
export GROFF_NO_SGR=1                  # for konsole and gnome-terminal
export MANPAGER='less -s -M +Gg';

# Reduce delay to 0.1 seconds for switching to normal mode with ESC
export KEYTIMEOUT=1

# Clean PATH and set this up correctly
# Check order -> system binaries > user binaries
PATH=
path-append "/usr/local/bin" \
            "/usr/bin" \
            "/usr/local/sbin" \
            "/usr/sbin" \
            "/usr/lib/jvm/default/bin" \
            "/usr/bin/site_perl" \
            "/usr/bin/vendor_perl" \
            "/usr/bin/core_perl" \
            "/opt/cuda/bin" \
            "$HOME/bin" \
            "$HOME/.gem/ruby/2.5.0/bin"

export PATH=$PATH

# Make sure systemd is aware of our current environment.
# No PATH modifications after this line
systemctl --user import-environment PATH

## ============================================================================
##                              Auto Completion
## ============================================================================

# Enable some Bash 4 features when possible:
# * `autocd`,
# e.g. `**/qux` will enter `./foo/bar/baz/qux` * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
    shopt -s "$option" 2> /dev/null;
done;

# Add tab completion for many Bash commands
if [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion;
fi


# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Add tab completion for `defaults read|write NSGlobalDomain` You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults;


